configuration:
  projectName: sampleconfigclient
server:  
  port: 8088
---
spring:
  profiles: development
server:  
  port: 8080
debug: true 
---
spring:
  profiles: production
server:  
  port: 8087
