datasource:
  url: jdbc:mysql://localhost:3306/default?useSSL=false
  username: root_default
  password: root_default
---
spring:
  profiles: development
datasource:
  url: jdbc:mysql://localhost:3306/dev?useSSL=false
  username: root_dev
  password: root_dev
---
spring:
  profiles: production
datasource:
  url: jdbc:mysql://localhost:3306/prod?useSSL=false
  username: root_prod
  password: root_prod
