datasource:
  url: jdbc:mysql://localhost:3306/default_sample?useSSL=false
  username: root_default_sample_change_
  password: root_default_sample_change_
---
spring:
  profiles: development
datasource:
  url: jdbc:mysql://localhost:3306/dev_sample?useSSL=false
  username: root_dev_sample_c
  password: root_dev_sample_c
server:
  port: 9002
---
spring:
  profiles: production
datasource:
  url: jdbc:mysql://localhost:3306/prod?useSSL=false
  username: root_prod_sample_c
  password: root_prod_sample_c
server:
  port: 9003
